language: node_js
matrix:
  include:
    - node_js: node # Current
    - node_js: --lts # LTS
      env: NPM_DEPLOY=true
    - node_js: 6 # Minimum required
install:
  - npm install --loglevel http # Prevent timeouts for inactivity
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: amercier/eslint-config-jsdoc-strict # Prevents publishing on PRs
    condition: $NPM_DEPLOY = true # Prevents publishing on each matrix build
cache:
  directories:
    - $HOME/.npm
